/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hehoe_purple_signal_PurpleSignal */

#ifndef _Included_de_hehoe_purple_signal_PurpleSignal
#define _Included_de_hehoe_purple_signal_PurpleSignal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hehoe_purple_signal_PurpleSignal
 * Method:    handleMessageNatively
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_de_hehoe_purple_1signal_PurpleSignal_handleMessageNatively
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
